# Generated by Django 5.1 on 2024-08-28 12:42

import airport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0003_alter_ticket_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplane",
            name="image",
            field=models.ImageField(
                null=True,
                upload_to=airport.models.image_path
            ),
        ),
        migrations.AddField(
            model_name="airport",
            name="image",
            field=models.ImageField(
                null=True,
                upload_to=airport.models.image_path
            ),
        ),
    ]
